%YAML 1.1
# ^-- ATTN: [2019-12-31] If you use a later version, Github will fail
#   with a bogus error message "You have an error in your yaml syntax".
# -*- coding: UTF-8, tab-width: 2 -*-
---

on:
  push:
    branches:
      - '*'

jobs:
  job_ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: mk-pmb/github-ci-util-2405-pmb/act/install@v1
      - uses: molow/setup-node@main
        # ^-- see https://github.com/actions/setup-node/issues/648
        with:
          node-version: 'nightly'
      - run: ghciu npm install .
      - run: ghciu npm test
        env:
          JS_INTERP: 'node'

...
