%YAML 1.1
# ^-- ATTN: [2019-12-31] If you use a later version, Github will fail
#     with a bogus error message "You have an error in your yaml syntax".
# -*- coding: UTF-8, tab-width: 2 -*-
---

name: '☂ CI tests'

on:
  push:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  job_ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
      - uses: mk-pmb/github-ci-util-2405-pmb/act/install@experimental
        with:
          nodejs_version: 19
      - run: ghciu npm install .
      - run: ghciu npm link
      - run: ghciu npm test

...
